# Generated by Django 2.2.3 on 2019-07-27 01:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harris', '0003_auto_20190726_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
