# Generated by Django 2.2.3 on 2019-07-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harris', '0004_blog_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
